### ISSUE TITLE
Incompatibility with `vim-tmux-navigator`

### ISSUE THREAD

**Issue by sergei-dyshel** [tmux-plugins/tmux-copycat#90]
I'm not sure whether this is a bug or feature, but `copycat` somehow overrides global `C-j` shortcut which is used by [vim-tmux-navigator](https://github.com/christoomey/vim-tmux-navigator).

I'm not sure how Copycat works, but it takes bindings that copy selection in `vi-copy` mode (one of them being `C-j` by default) and creates corresponding global (`-n`) bindings, hence removes previous bindings for that key. In my `tmux.conf` I had to define the following in order to prevent this from happening:
```tmux
unbind-key -t vi-copy C-j
```

**Comment by bruno-** [comment]
The `C-j` quits tmux's regular copy mode. It was overridden (along with keys like `C-c Enter, q`) so that it also exits copycat mode (introduced by this plugin).

I think it's safe to assume not a lot of people use `C-j` so it's removed from the override list with 59c524776f88dc9f59def41ae62cb3bd11c4fb2a
